#
# Configuration for Alacritty, the GPU enhanced terminal emulator.
# Sources:
#   - https://github.com/alacritty/alacritty/blob/master/alacritty.yml
#   - https://gist.github.com/ruddra/900e48cb65645ccfcf57545c7e192972
#
shell:
  program: /usr/bin/fish

# $TERM=alacritty doesn't advertise true colors.
# Setting it to a terminal value that does will
# allow applications to use all colors.
env:
  TERM: xterm-256color

window:
  padding:
    x: 15
    y: 15
  opacity: 0.9
  dynamic_padding: true
  decorations: none

font:
  size: 10.0
  normal:
    family: Source Code Pro
    style: Regular
  bold:
    family: Source Code Pro
    style: Bold
  italic:
    family: Source Code Pro
    style: Italic
  bold_italic:
    family: Source Code Pro
    style: Bold Italic

# Colors (Gruvbox dark)
# https://github.com/morhetz/gruvbox
colors:
  primary:
    background:        '#282828'
    foreground:        '#ebdbb2'
    bright_foreground: '#fbf1c7'
    dim_foreground:    '#a89984'
  search:
    matches:
      foreground: '#282828'
      background: '#ebdbb2'
    focused_match:
     foreground: CellBackground
     background: CellForeground
    bar:
      background: '#ebdbb2'
      foreground: '#282828'
  line_indicator:
    foreground: None
    background: None
  selection:
    text:       CellBackground
    background: CellForeground
  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'
  normal:
    black:   '#282828'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'
  dim:
    black:   '#32302f'
    red:     '#9d0006'
    green:   '#79740e'
    yellow:  '#b57614'
    blue:    '#076678'
    magenta: '#8f3f71'
    cyan:    '#427b58'
    white:   '#928374'

  # https://www.ditig.com/256-colors-cheat-sheet
  # https://en.wikipedia.org/wiki/X11_color_names
  # https://jonasjacek.github.io/colors/
  indexed_colors:
    - { index: 16, color: '0xfe8019' }
    - { index: 17, color: '0xd65d0e' }
    - { index: 18, color: '0x3c3836' }
    - { index: 19, color: '0x504945' }
    - { index: 20, color: '0xbdae93' }
    - { index: 21, color: '0xebdbb2' }

# Disable URL highlighting.
hints:
  enabled: []
