# Configuration for Alacritty, the GPU enhanced terminal emulator.
# Sources:
#   - https://github.com/alacritty/alacritty/blob/master/alacritty.yml
#   - https://gist.github.com/ruddra/900e48cb65645ccfcf57545c7e192972
live_config_reload: true

# $TERM=alacritty doesn't advertise true colors.
# Setting it to a terminal value that does will
# allow applications to use all colors.
env:
  TERM: xterm-256color
  ZDOTDIR: ~/.config/zsh/zshrc

background_opacity: 0.9

window:
  padding:
    x: 15
    y: 15
  dynamic_padding: true
  decorations: none

scrolling:
  history: 10000
  # Lines per scroll.
  multiplier: 3

font:
  size: 11.0

  normal:
    family: Source Code Pro
    style: Regular

  bold:
    family: Source Code Pro
    style: Bold

  italic:
    family: Source Code Pro
    style: Italic

  bold_italic:
    family: Source Code Pro
    style: Bold Italic

# Colors (Gruvbox dark)
colors:
  primary:
    # hard contrast background - '#1d2021'
    background:        &gruvbox_dark_bg '#282828'
    # soft contrast background - '#32302f'
    foreground:        '#ebdbb2'
    bright_foreground: '#fbf1c7'
    dim_foreground:    '#a89984'
  cursor:
    text:   CellBackground
    cursor: CellForeground
  search:
    matches:
      foreground: '#282828'
      background: '#ebdbb2'
    focused_match:
     foreground: CellBackground
     background: CellForeground
    bar:
      background: '#ebdbb2'
      foreground: '#282828'
  line_indicator:
    foreground: None
    background: None
  selection:
    text:       CellBackground
    background: CellForeground
  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'
  normal:
    black:   *gruvbox_dark_bg
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'
  dim:
    black:   '#32302f'
    red:     '#9d0006'
    green:   '#79740e'
    yellow:  '#b57614'
    blue:    '#076678'
    magenta: '#8f3f71'
    cyan:    '#427b58'
    white:   '#928374'

  hints:
    start:
      foreground: '#1d1f21'
      background: '#e9ff5e'
    end:
      foreground: '#e9ff5e'
      background: '#1d1f21'

  # https://www.ditig.com/256-colors-cheat-sheet
  # https://en.wikipedia.org/wiki/X11_color_names
  indexed_colors:
    - { index: 16, color: '0xfe8019' }
    - { index: 17, color: '0xd65d0e' }
    - { index: 18, color: '0x3c3836' }
    - { index: 19, color: '0x504945' }
    - { index: 20, color: '0xbdae93' }
    - { index: 21, color: '0xebdbb2' }

bell:
  duration: 0  # Disabled.

selection:
  save_to_clipboard: false

cursor:
  style:
    shape: Block
    blinking: Off

  # Cursor becomes empty box when it is out of focus.
  unfocused_hollow: true

  # This is for non-block cursors.
  # thickness: 0.15

shell:
  program: /usr/bin/fish

# Start shell in parent process's working directory.
working_directory: None

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: false

# Regex hints
# https://github.com/alacritty/alacritty/blob/master/alacritty.yml#L458
# TODO: Consider a Wayland-native alternative to xdg-open? (swaymsg exec?)
hints:
  enabled:
   - regex: "(https:|http:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
     command: xdg-open
     post_processing: true
     mouse:
       enabled: true
       mods: None
     binding:
       key: U
       mods: Control|Shift

# Mouse bindings
# https://github.com/alacritty/alacritty/blob/master/alacritty.yml#L502

# Key bindings
# https://github.com/alacritty/alacritty/blob/master/alacritty.yml#L534
